### ISSUE TITLE
Standardize application structure across Coral Go programs

### ISSUE THREAD

**Issue by jde** [coralproject/pillar#24]
from @ardan-bkennedy 
I also suggest reworking the source tree of the three Go projects to be the same as well.

app
cmd
pkg
vendor
config
tstdata

A repo is a project and a project has a single vendor folder.

Moved from #21

**Comment by samshub** [comment]
Changes made.

**Comment by ardan-bkennedy** [comment]
@sam You don't want a model and service package under pkg.  Packages provide something and that should drive the API. Those code files should come under a single package. The models would not be used outside the code inside of service. All that code should be together in a single package.

**Comment by ardan-bkennedy** [comment]
@sam The tests for the package must be with the package. Because then when the package is downloaded you can't run the tests.

**Comment by ardan-bkennedy** [comment]
@sam can we also use the same log, cfg and web packages from kit? I can help you get that vendored and setup.

Also please make sure you are running all the code through golint.

**Comment by samshub** [comment]
Yeah, service and test should go with the app itself. I must say there is value in keeping model under pkg. As for the log, web etc. I have #6 and #23 open.

**Comment by ardan-bkennedy** [comment]
I think service and model should be brought together under a single package that can live under pkg. This is because if you were to write a cli tool, both the cli tool and web app would need this. Those packages that are reusable belong under pkg. You can't have service without model and nothing will ever import model without using service. You really want to look at your models and see what aspects can be used on its own and what can't.

If you look at the pkg folder under xenia, you will see how functionality that is stand alone is separated. The models are driving the packages and the organization of that code.

**Comment by samshub** [comment]
Agreed, I'll make the changes suggested.
