### ISSUE TITLE
Move config code into pillar app

### ISSUE THREAD

**Issue by samshub** [coralproject/pillar#33]
> The code in config should move into pillar/app/pillar
> make crud independent of config code

**Comment by ardan-bkennedy** [comment]
Since those packages are tied to Pillar and only Pillar, and since all the code we write is using the same config package, you should rethink this. Decoupling config brings complexity and should be reserved for packages that can be used and live outside of Pillar.

In these cases you will also need to decouple logging because you can't assume the user of this package wants to use your logging package as well.

None of the packages in your project (repo) should have to worry about decoupling themselves from config and log.

What config settings are being directly accessed from the config package by your CRUD packages?

**Comment by samshub** [comment]
Yes, that's exactly what I'm trying to do here. Post refactoring, crud remains a stand-alone package that can be reused. All it needs is a mongo connection, which is provided via environment.

**Comment by ardan-bkennedy** [comment]
If you are talking about creating a set of packages for both Pillar and Sponge to use, then you need another repo. In this case these packages can still share the use of the same config and log packages or completely decouple themselves from them. This is now getting more complicated.

I think it is best to merge Sponge and Pillar together in the same Project (repo) and then they can share within the scope of the project these API's you both need.
