### ISSUE TITLE
How should we go microservice?

### ISSUE THREAD

**Issue by jde** [coralproject/pillar#65]
The signs and omens are clear, the time has come to adopt a microservice architecture and start developing our messaging protocol.

This is a discussion thread to track the conversation.  Go!

**Comment by jde** [comment]
The first candidate for a microservice is our stats aggregation.  Currently, we have an aggregation system that is well suited for real-time aggregations but only driven by a batch paradigm in Pillar.

https://github.com/coralproject/pillar/tree/master/app/stats

This functionality could be refactored into a set of individual aggregation services that listen for changes to the data and update aggregations.

**Comment by samshub** [comment]
To begin with, we need a pub-sub model that allows not-only processing with aggregation services, but also with any other services down the line such as moderation queues and so on. This will help us build a loosely-coupled (solid, that is) architecture that allows extensibility and flexibility.

Let me introduce (Kafka)[http://kafka.apache.org/], a modern/distributed messaging system. Here are some interesting reads:

* (Ecosystem)[https://cwiki.apache.org/confluence/display/KAFKA/Ecosystem]
* (Papers, presentation and more)[https://cwiki.apache.org/confluence/display/KAFKA/Kafka+papers+and+presentations]

Obviously we need to support smaller media org with limited technical strength. Turns out Kafka can be deployed in a (single docker container)[https://github.com/spotify/docker-kafka].
